name: omret
version: 1

libraries:
 - name: "django"
   version: "1.5"

##------static dir example-----
#handlers:
# - url: /static
#   static_dir : terryspace/static

handlers:
 - url: /static
   static_dir: omret/static